# Generated by Django 4.0.4 on 2022-06-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='department_app.department'),
        ),
    ]
