# Generated by Django 4.0.4 on 2022-06-16 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_status', models.CharField(choices=[('new', 'New'), ('inprogress', 'In progress'), ('cancelled', 'Cancelled'), ('finished', 'Finished'), ('frozen', 'Frozen')], default='new', max_length=25)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, max_length=400, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedprojects', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='department_app.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('inprogress', 'In progress'), ('cancelled', 'Cancelled'), ('finished', 'Finished'), ('frozen', 'Frozen')], default='new', max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.TextField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedtasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_app.project')),
            ],
        ),
    ]
