# Generated by Django 4.0.4 on 2022-06-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0004_alter_project_client_alter_project_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_app', to='client_app.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_app', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
