# Generated by Django 4.0.4 on 2022-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('new', 'New'), ('inprogress', 'In progress'), ('cancelled', 'Cancelled'), ('finished', 'Finished'), ('frozen', 'Frozen')], default='new', max_length=25),
        ),
    ]
