# Generated by Django 4.0.4 on 2022-06-26 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project_app.models
import project_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0008_alter_project_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project_app.models.get_upload_path, validators=[project_app.validators.validate_file_size, project_app.validators.validate_file_type])),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
