# Generated by Django 4.0.4 on 2022-06-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('project_app', '0010_alter_project_department_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_app', to='client_app.client'),
        ),
    ]
